<link rel="stylesheet" href="//cdn.datatables.net/1.10.3/css/jquery.dataTables.min.css">
<!--
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->baseUrl;?>/js/datatables/media/css/jquery.dataTables.css">
-->
<div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php">Home</a></p> &gt; <h2>Contatti</h2>
</div>
<table id="contactT">
   	<thead>
		<tr>
			<th data-bSortable="false" data-sName="id" data-bVisible="false">Id</th>
			<th data-sName="name" data-sClass="editable">Nome</th>
                        <th data-sName="datetime" data-sClass="editable">Data e ora</th>
                        <th data-sName="message" data-sClass="editable">Messaggio</th>
                        <th data-bSortable="false" data-sName="actions" >Azioni</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td colspan="6" class="dataTables_empty">Carico i dati</td>
		</tr>
	</tbody>
	<tfoot>
		<tr>
                        <th>Id</th>
			<th>Nome</th>
			<th>Data e ora</th>
                        <th>Messaggio</th>
                        <th>Azioni</th>
		</tr>
	</tfoot>
</table>