<?php if($GLOBALS['db']->config->useCDN === true) : ?>
<script src="//cdn.datatables.net/1.10.3/js/jquery.dataTables.min.js"></script>
<script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<script src="//cdn.jsdelivr.net/jquery.jeditable/1.7.3/jquery.jeditable.js"></script>
<script src="//cdn.jsdelivr.net/plupload/2.1.2/plupload.full.min.js"></script>
<script src="//cdn.jsdelivr.net/plupload/2.1.2/jquery.ui.plupload/jquery.ui.plupload.min.js"></script>
<script src="//cdn.jsdelivr.net/plupload/2.1.2/i18n/it.js"></script>
<?php else : ?>
<script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/DataTables/media/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/tinymce-dist/tinymce.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/tinymce-dist/tinymce.jquery.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/plupload/js/plupload.full.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/plupload/js/jquery.ui.plupload/jquery.ui.plupload.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/jquery_jeditable/jquery.jeditable.js"></script>
<script src="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('js/plupload/js/i18n/it.js'); ?>"></script>
<script src="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('js/common/tinymce/langs/it.js'); ?>"></script>
<?php endif; ?>
<script src="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('js/administrator/dictionary.js'); ?>"></script>