<?php if($GLOBALS['db']->config->useCDN === true) : ?>
<link rel="stylesheet" href="//cdn.datatables.net/1.10.3/css/jquery.dataTables.min.css">
<?php else : ?>
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->baseUrl;?>/js/DataTables/media/css/jquery.dataTables.css">
<?php endif; ?>
<div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php">Home</a></p> &gt; <h2>Vocabolario</h2>
</div>
<?php
$role = $GLOBALS['profile']->getRole();
if ($role->getData('id') >0 && $role->getData('id') <= 1) : ?>
<a class="actions add" title="Aggiungi" href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=dictionary&amp;action=edit">Aggiungi</a><br/>
<?php endif; ?>
<table id="dictionary">
   	<thead>
		<tr>
			<th data-sName="id" >Id</th>
			<th data-sName="term" >Termine</th>
			<th data-sName="abbreviation" >abbreviazione</th>
                        <th data-sName="description" >Descrizione</th>
                        <th data-bSortable="false" data-sName="actions" >Azioni</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td colspan="6" class="dataTables_empty">Carico i dati</td>
		</tr>
	</tbody>
	<tfoot>
		<tr>
			<th>Id</th>
			<th>Termine</th>
			<th>Abbreviazione</th>
                        <th>Descrizione</th>
                        <th>Azioni</th>
		</tr>
	</tfoot>
</table>