<div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php">Home</a></p> &gt; <h2>Backup / Restore</h2>
</div>
<ul>
    <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=backup&action=backuptaxa" class="blank">Backup taxa</a></li>
    <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=backup&action=backuputenti" class="blank">Backup utenti</a></li>
    <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=backup&action=resettaxa" class="resetTaxa">Reset taxa</a></li>
    <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=backup&action=resetutenti" class="resetUtenti" >Reset utenti</a></li>
    <li>
    <form class="uploadForm" method="post" action="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=backup">
    <div id="container">
       <a id="pickfiles" href="#">Seleziona il file per il ripristino</a>
    </div>
    <input type="hidden" id="filename" name="filename" value=""/>
    </form>
    </li>
    <img class="restoreAjaxLoader" src="<?php echo $GLOBALS['db']->config->baseUrl;?>/style/general/images/ajax-loader.gif" style="display: none;">
    <?php if ($GLOBALS['db']->config->background->useAJAX == true) :?>
    <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=backup&action=reindex_ajax" class="reindexAJAX" >Indicizza</a></li>
    <img class="reindexAjaxLoader" src="<?php echo $GLOBALS['db']->config->baseUrl;?>/style/general/images/ajax-loader.gif" style="display: none;">
    <?php else : ?>
    <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=backup&action=reindex" class="reindex" >Indicizza</a></li>
    <?php endif; ?>
</ul>
<?php 
$logFilename = $GLOBALS['db']->baseDir.DIRECTORY_SEPARATOR.'log'.DIRECTORY_SEPARATOR.'reindex.txt';
if ($GLOBALS['db']->config->background->useAJAX != true && is_file($logFilename)) : ?>
<p>Ultima indicizzazione</p>
<pre><?php echo file_get_contents($logFilename); ?></pre>
<?php endif; 
if ($GLOBALS['db']->config->background->useAJAX == true ) : ?>
<div id="reindexLog"/>
<?php endif;
 