<div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>/user.php">Home</a></p> &gt; <h2>Modifica password</h2>
</div>
<form method="post" action="#">
   <div>
   <label for="old_password">Vecchia password</label>
   <input id="old_password" autocomplete="off" name="old_password" value="" type="password">
   </div>
   <div>
   <label for="new_password">Nuova password</label>
   <input id="new_password" autocomplete="off" name="new_password" value="" type="password">
   </div>
   <div>
   <label for="new_passwordr">Ridigita la nuova password</label>
   <input id="new_passwordr" autocomplete="off" name="new_passwordr" value="" type="password">
   </div>
   <div>
      <input type="submit" name="submit" value="Salva">
   </div>
</form>
