<?php if ($this->getControl()->formIsValid()) : ?>
<h2>Benvenuto su <?php echo $GLOBALS['config']->siteName; ?></h2>
<p>Potrai registrare le tue osservazioni botaniche e aiutarci a mantenere aggiornato <?php echo $GLOBALS['config']->siteName; ?></p>
<?php else : ?>
<h2>Attenzione</h2>
<?php foreach ($this->getControl()->getValidationMessages() as $message) : ?>
<p><?php echo $message;?></p>
<?php endforeach ;
endif; ?>
