<ul>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>user.php?task=changeprofile">Profilo</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>user.php?task=changepassword">Modifica password</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>user.php?task=changelogin">Cambia email/nome utente</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>user.php?task=observation">Osservazioni</a></li>
</ul>