<h2>Inserisci le tue credenziali</h2>
<form action="<?php echo $GLOBALS['db']->config->baseUrl;?><?php echo $GLOBALS['control']->getPage();?>" method="post">
   <input type="hidden" name="action" value="login" />
   <div>
   <label for="username_login">Nome utente/Email</label>
   <input type="email" name="username" id="username_login" value="" />
   </div>
   <div>
   <label for="password_login">Password</label>
   <input type="password" name="password" id="password_login" value="" />
   </div>
   <input type="submit" name="login" value="Accedi">
</form>
<h2>Dimenticato le credenziali? Crea una nuova password.</h2>
<form action="<?php echo $GLOBALS['db']->config->baseUrl;?><?php echo $GLOBALS['control']->getPage();?>" method="post">
   <input type="hidden" name="task" value="recover" />
   <div>
   <label for="recover_login">Email</label>
   <input type="email" name="recover_login" id="recover_login" value="" />
   </div>
   <input type="submit" name="submit" value="Recupera">
</form>
<h2>Non sei registrato, iscriviti.</h2>
<p>Potrai raccogliere le tue osservazioni botaniche, segnalare eventuali errori e collaborare a la chiave della Flora d'Italia</p>
<form action="<?php echo $GLOBALS['db']->config->baseUrl;?><?php echo $GLOBALS['control']->getPage();?>" method="post">
   <input type="hidden" name="action" value="register" />
   <div>
   <label for="username_register">Nome utente/Email</label>
   <input type="email" name="username" id="username_register" value="" />
   </div>
   <div>
   <label for="password_register">Password</label>
   <input type="password" name="password" id="password_register" value="" />
   </div>
   <div>
   <label for="passwordr_register">Ripeti la password</label>
   <input type="password" name="passwordr" id="passwordr_register" value="" />
   </div>
   <input type="submit" name="register" value="Registrati">
</form>
<p>Attiva il tuo utente, segui istruzioni nella mail che ti verrà inviata</p>