<fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
Accedi tramite facebook
</fb:login-button>
<p>o inserisci le tue credenziali</p>
<form action="<?php echo $GLOBALS['db']->config->baseUrl;?><?php echo $GLOBALS['control']->getPage();?>" method="post">
   <input type="hidden" name="action" value="login" />
   <?php if (array_key_exists('return_url', $_REQUEST) && $_REQUEST['return_url'] != '') : ?>
   <input type="hidden" name="return_url" id="return_url" value="<?php echo $_REQUEST['return_url'];?>" />
   <?php endif; ?>    
   <div>
   <label for="username_login">Nome utente/Email</label>
   <input type="email" name="username" id="username_login" tabindex="1" value="" />
   <a href="#" id="lost_password_link">Hai dimenticato la password?</a>
   </div>
   <div>
   <label for="password_login">Password</label>
   <input type="password" name="password" id="password_login" tabindex="2" value="" />
   <a href="#" id="subscribe_link">Non sei iscritto?</a>
   </div>
   <input type="submit" name="login" value="Accedi">  
   <div id="status">
</form>
<form id="lost_password_form" action="<?php echo $GLOBALS['db']->config->baseUrl;?><?php echo $GLOBALS['control']->getPage();?>" method="post">
    <p>Dimenticato le credenziali? Crea una nuova password.</p>
   <input type="hidden" name="task" value="recover" />
   <div>
   <label for="recover_login">Email</label>
   <input type="email" name="recover_login" id="recover_login" value="" />
   </div>
   <input type="submit" name="submit" value="Recupera">
</form>
<form id="subscribe_form" action="<?php echo $GLOBALS['db']->config->baseUrl;?><?php echo $GLOBALS['control']->getPage();?>" method="post">
   <p>Non sei registrato, iscriviti.</p>
   <p>Potrai raccogliere le tue osservazioni botaniche, segnalare eventuali errori e collaborare a la chiave della Flora d'Italia</p>
   <input type="hidden" name="action" value="register" />
   <div>
   <label for="username_register">Nome utente/Email</label>
   <input type="email" name="username" id="username_register" value="" />
   </div>
   <div>
   <label for="password_register">Password</label>
   <input type="password" name="password" id="password_register" value="" />
   </div>
   <div>
   <label for="passwordr_register">Ripeti la password</label>
   <input type="password" name="passwordr" id="passwordr_register" value="" />
   </div>
   <div>
   <?php 
   $firstNumber = rand(0,9);
   $secondNumber = rand(0,9);
   ?>
   <label for="check"><?php echo $GLOBALS['numberAsLetters'][$firstNumber];?> + <?php echo $GLOBALS['numberAsLetters'][$secondNumber];?></label>
   <input type="number" name="check" id="check" value="" />   
   <input type="hidden" name="expected" id="expected" value="<?php echo base64_encode($firstNumber+$secondNumber);?>" />   
   </div>
   <input type="submit" name="register" value="Registrati">
   <p>Attiva il tuo utente, segui istruzioni nella mail che ti verrà inviata</p>
</form>
