<script src="//cdn.datatables.net/1.10.3/js/jquery.dataTables.min.js"></script>
<!--
<script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/DataTables/media/js/jquery.dataTables.min.js"></script>
-->
<script src="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('js/jeditable/jquery.jeditable.mini.js');?>"></script>
<script src="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('js/administrator/region.js');?>"></script>