<!-- Make sure you put this AFTER Leaflet's CSS -->
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
  integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
  crossorigin=""></script>
<?php if($GLOBALS['db']->config->useCDN === true) : ?>
<script src="//cdn.jsdelivr.net/fancybox/2.1.5/jquery.fancybox.pack.js"></script>
<script src="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('js/observation.min.js.gz');?>"></script>
<?php else : ?>
<script type="text/javascript" src="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('/js/fancyBox/source/jquery.fancybox.pack.js');?>"></script>
<script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/dictionary.js"></script>
<?php endif; ?>
