<?php
if (!isset( $termColl)) {
   $termColl = $this->object;
}
$pageBuffer=5;
$lastPage = intval($termColl->countAll(array('valid'=>true))/$_REQUEST['pagelength'])-1;
$GLOBALS['lastPage']=$lastPage;
$currentpage=min($lastPage,intval($_REQUEST['start']/$_REQUEST['pagelength']));
$pages =array(0,$lastPage);
$pages = array_merge($pages,range($currentpage-$pageBuffer,$currentpage+$pageBuffer));
$pages=array_unique($pages);
$pages=array_filter($pages, function($val){return $val >= 0 && $val <=$GLOBALS['lastPage'];});
sort($pages);
?>
<div id="paginationContainer">
<?php foreach($pages as $page):
    $class='';
    if ($page == $currentpage) {
        $class=' selectedPage';
    }
    ?>
    <a href="?start=<?php echo $page*$_REQUEST['pagelength'].(array_key_exists('text', $_REQUEST) ? '&amp;text='.$_REQUEST['text']: '')?>" class="pageSelector<?php echo $class;?>" data-page="<?php echo $page*$_REQUEST['pagelength'];?>"><?php echo $page+1;?></a>
    <?php if ($page <$lastPage && !in_array($page+1, $pages)) :?>…<?php endif;?>
<?php endforeach; ?>
</div>
<?php
$radius = 12;
$pointsString='[';
foreach ($termColl->getItems() as $index=>$term):?>
<div>
    <p><strong><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>dictionary.php?id=<?php echo $term->getData('id');?>"><?php echo $term->getData('term'); ?></a></strong></p>
    <p><em><?php echo $term->getData('abbreviation'); ?></em></p>
    <p><?php echo $term->getData('description'); ?></p>
    <?php $termImage = $term->getTermImageColl(array('iDisplayStart'=>0,'iDisplayLength'=>1))->getFirst();
    $thumbnailImageUrl = null;
    try {
    $thumbnailImageUrl = $termImage->getUrl(array('x'=>300,'y'=>200));
    } catch (Exception $e) {}
    if (!is_null($thumbnailImageUrl)) : ?>
    <a class="fancybox" href="<?php echo $termImage->getUrl(); ?>">
    <img src="<?php echo $thumbnailImageUrl; ?>">
    </a>
    <?php endif; ?>
</div>
<?php endforeach;