<?php

namespace floraobservation;
if (!class_exists('Autoload')) {
   require __DIR__.'/../../../config/config.php';
   require __DIR__.'/../../../lib/floraobservation/Autoload.php';
   \floraobservation\Autoload::getInstance();
   $loader = new \Zend\Loader\StandardAutoloader(array(
    'autoregister_zf' => true,
    'fallback_autoloader' => true
   ));
   $loader->register();

   $config = new \Zend\Config\Config($configArray);
   $GLOBALS['db'] = new \Zend\Db\Adapter\Adapter($config->database->toArray());
   $GLOBALS['db']->baseDir=__DIR__.'/../../../';
   
}

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-26 at 08:51:47.
 */
class TaxaObservationTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var TaxaObservation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TaxaObservation($GLOBALS['db']);
        $GLOBALS['db']->query('DELETE FROM `taxa_observation` WHERE `id` = 1' , \Zend\Db\Adapter\Adapter::QUERY_MODE_EXECUTE);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers floraobservation\TaxaObservation::insert
     * @todo   Implement testInsert().
     */
    public function testInsert() {
        $this->object->setData(array(
            'id'=>1,
            'taxa_id'=>1,
            'profile_id'=>1,
            'title'=>'Test',
            'description'=>'Test',
            'latitude'=>45.124536,
            'longitude'=>12.458975
        ));
        $this->object->insert();
        $this->object->loadFromId(1);
        var_dump($this->object->getData());
    }

}
