<div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php">Home</a></p> &gt; <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=taxa">Elenco dei taxa</a></p> &gt; <h2>Modifica chiave dicotomica</h2>
</div>
<?php $taxa = $this->object; ?>
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->baseUrl.$GLOBALS['template']->getUrlModifyTimestamp('/style/administrator/taxa.css');?>">
<form method="post" action="#">
   <input type="submit" name="submit" value="Salva">
   <input type="hidden" name="id" id="id" value="<?php echo $taxa->getData('id');?>">
<?php if ($taxa->getData('id') > 1) : ?>
<a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=taxa&action=edit&id=<?php echo $taxa->getData('id')?>">Modifica taxa</a>
<?php endif; ?>
<a class="actions update" href="#" title="Aggiorna">Aggiorna</a>
<a class="hideMissing actions hide" href="#" title="Nascondi mancanti">Nascondi mancanti</a>
<a class="deleteButton actions delete" href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=dico&amp;action=delete&amp;id=<?php echo $taxa->getData('id');?>" title="Cancella">Cancella</a>
<div>
<div>
   <input class="addText" name="addText">
   <p id="dico_error" style="display: none;">Indicare il titolo dell'elemento</p>
   <span>
   <input type="hidden" name="addPhotoId">    
   <a class="uploadImage" href="#">Carica immagine</a>
   </span>
   <a class="addDico" href="#">Aggiungi elemento</a>
</div>
<?php
$dicoItemColl = $taxa->getDicoItemColl();
$positions = array();
$lastPosition = 0;
foreach ($dicoItemColl->getItems() as $id => $dicoItem):?>
<div id="dicoList">
   <?php echo $id+1; ?>
   <input name="text[]" value="<?php echo $dicoItem->getData('text');?>"> 
   <?php if ($dicoItem->getRawData('name') == '') : ?>
   <a class="addTaxaButton actions add" href="#"title="Aggiungi Taxa">Aggiungi Taxa</a>
   <span style="display:none;" class="addTaxa" method="post" action="?task=taxa&amp;action=edit&amp;children_dico_id=<?php echo $taxa->getData('id');?>&amp;children_dico_item_id=<?php echo $dicoItem->getData('id');?>">
      <input name="children_dico_item_id[]" value="<?php echo $dicoItem->getData('id');?>"/>
      <input class="taxaName" name="name[]"/>
      <a class="createTaxa" title="Premi CTRL per copiare il nome senza creare l'associazione con il taxa"/>
      <a class="restoreTaxaButton actions close" href="#" title="Chiudi">Chiudi</a>
   </span>
   <?php else: ?>
   <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=taxa&amp;action=edit&amp;id=<?php echo $dicoItem->getData('taxa_id');?>"><?php echo $dicoItem->getRawData('initials');?> <?php echo $dicoItem->getRawData('name');?></a>
   <a class="deleteTaxaAssociation actions delete" href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=dico&amp;action=deletetaxaassociation&amp;id=<?php echo $taxa->getData('id');?>&amp;children_dico_item_id=<?php echo $dicoItem->getData('id');?>" title="Cancella associazione">Cancella associazione</a>
   <?php endif; ?>
   <span>
   <input type="hidden" name="photo_id[]">    
   <a class="uploadImage" href="#">Carica immagine</a>
   </span>
   <a class="deleteTaxaItem actions delete" href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=dico&amp;action=deletetaxaitem&amp;id=<?php echo $taxa->getData('id');?>&amp;children_dico_item_id=<?php echo $dicoItem->getData('id');?>" title="Cancella voce">Cancella voce</a>
</div>
<?php endforeach; ?>
</div>
<input type="submit" name="submit" value="Salva">
</form>
<a class="actions update" href="#" title="Aggiorna">Aggiorna</a>
<a class="deleteButton actions delete" href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=dico&amp;action=delete&amp;id=<?php echo $taxa->getData('id');?>" title="Cancella">Cancella</a>