<div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>/administrator.php">Home</a></p> &gt; <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>/administrator.php?task=dico">Elenco delle chiavi dicotomiche</a></p> &gt; <h2>Modifica una chiave dicotomica</h2>
</div>
<?php
$dico = $this->object;
$dicoItemColl = $dico->getDicoItemColl();
foreach ($dicoItemColl->getItems() as $dicoItem): 
   $label = $dicoItem->getData('text');
   $editable='';
   if ($dicoItem->getRawData('incomplete') == 1)
      $editable='class="editable"';
?>
<form>
   <input type="hidden" name="id" id="id" value="<?php echo $dico->getData('id');?>">
</form>
<p id="d<?php echo $dicoItem->getData('id'); ?>" <?php echo $editable;?>><?php echo $label;?></p>
<?php endforeach; ?>
