<div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>/administrator.php">Home</a></p> &gt; <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>/administrator.php?task=dico">Elenco delle chiavi dicotomiche</a></p> &gt; <h2>Modifica una chiave dicotomica</h2>
</div>
<?php
$dico = $this->object;
?>
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->baseUrl;?>/style/administrator/taxa.css">
<form method="post" cation="#">
   <input type="hidden" name="id" id="id" value="<?php echo $dico->getData('id');?>">
</form>
<?php
$dicoItemColl = $dico->getDicoItemColl(true);
foreach ($dicoItemColl->getItems() as $dicoItem): 
   $label = $dicoItem->getData('text');
   $missing='';
   if ($dicoItem->getRawData('incomplete') == 1)
      $missing=' missing';
?>
<div>
   <?php echo str_repeat('&#160;', strlen($dicoItem->getData('id'))-1); ?>
   <?php echo strlen($dicoItem->getData('id')); ?>
   <span id="d<?php echo $dicoItem->getData('id'); ?>" class="editable<?php echo $missing;?>"><?php echo $label;?></span>
   <?php if($dicoItem->getRawData('possible_taxa') === true) : ?>
   <a class="addTaxaButton" href="#">Aggiungi Taxa</a>
   <form style="display:none;" class="addTaxa" method="post" action="?task=taxa&amp;action=edit&amp;children_dico_id=<?php echo $dico->getData('id');?>&amp;children_dico_item_id=<?php echo $dicoItem->getData('id');?>">
      <input class="taxaName" name="name"/>
      <input type="submit" name="submit" value="Crea"/>
      <a class="restoreTaxaButton" href="#">Chiudi</a>
   </form>
   <?php else: 
      $taxa = $dicoItem->getTaxa();?>
   <a class="restoreTaxaButton" href="<?php echo $GLOBALS['db']->config->baseUrl;?>/administrator.php?task=taxa&amp;action=edit&amp;id=<?php echo $taxa->getData('id');?>"><?php echo $taxa->getData('taxa_kind_initials');?> <?php echo $taxa->getData('name');?></a>
   <?php endif; ?>
</div>
<?php endforeach; ?>
