<?php $role = $GLOBALS['profile']->getRole();?>
<ul>
   <?php if ($role->getData('id') >0 && $role->getData('id') <= 2) : ?>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=taxa">Taxa</a></li>
   <?php endif; ?>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=observation">Osservazioni</a></li>
   <?php if ($role->getData('id') >0 && $role->getData('id') <= 1) : ?>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=taxa_category">Raggruppamenti sistematici</a></li>
   <?php endif; ?>
   <?php if ($role->getData('id') >0 && $role->getData('id') <= 1) : ?>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=attribute">Attributi</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=region">Regioni</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=user">Utenti</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=content">Contenuti dinamici</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=contact">Contatti</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=link">Fornitore link esterni</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=log">Log</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=backup">Backup/Restore</a></li>
   <?php endif; ?>
</ul>
