<ul>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=dico">Chiavi dicotomiche</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=taxa_category">Raggruppamenti sistematici</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=taxa">Taxa</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=region">Regioni</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=user">Utenti</a></li>
</ul>