<?php
$taxaKind = new \flora\taxa\TaxaKind($GLOBALS['db']);
if (array_key_exists('id', $_REQUEST)) {
   $taxaKind->loadFromId($_REQUEST['id']);
}
?><div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php">Home</a></p> &gt; <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=taxa_category">Elenco dei raggruppamenti sistematici</a></p> &gt; <h2>Modifica un raggruppamento sistematico</h2>
</div>
<a id="sortCategoryTaxa" href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=taxa_category&amp;action=sort">Ordina le categorie</a>
<form method="post" action="#">
   <input type="hidden" id="id" name="id" value="<?php echo $taxaKind->getData('id')?>">
   <div>
   <label for="initials">Sigla</label>
   <input id="initials" name="initials" value="<?php echo $taxaKind->getData('initials')?>">
   </div>
   <div>
   <label for="name">Nome</label>
   <input id="name" name="name" value="<?php echo $taxaKind->getData('name')?>">
   </div>
   <div>
   <label for="description">Descrizione</label>
   <textarea id="description" name="description"><?php echo $taxaKind->getData('description')?></textarea>
   </div>
   <div>
      <input type="submit" name="submit" value="Salva">
   </div>
</form>
