<script src="//cdn.datatables.net/1.10.3/js/jquery.dataTables.min.js"></script>
<script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<!--
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/datatables/media/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/tinymce/tinymce.min.js"></script>
-->
<script src="<?php echo $GLOBALS['db']->config->baseUrl.$GLOBALS['template']->getUrlModifyTimestamp('js/tinymce/jquery.tinymce.min.js');?>"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl.$GLOBALS['template']->getUrlModifyTimestamp('js/common/tinymce/langs/it.js');?>"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl.$GLOBALS['template']->getUrlModifyTimestamp('js/administrator/taxa_category.js');?>"></script>