<link rel="stylesheet" href="js/dataTables/media/css/jquery.dataTables.css">
<div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>/administrator.php">Home</a></p> &gt; <h2>Raggruppamenti sistematici</h2>
</div>
<a id="addCategoryTaxa" href="<?php echo $GLOBALS['db']->config->baseUrl;?>/administrator.php?task=taxa_category&amp;action=edit">Aggiungi un raggruppamento</a>
<a id="sortCategoryTaxa" href="<?php echo $GLOBALS['db']->config->baseUrl;?>/administrator.php?task=taxa_category&amp;action=sort">Ordina</a>
<table id="categoryTaxa">
   	<thead>
		<tr>
			<th data-bSortable="false" data-sName="initials" >Sigla</th>
			<th data-bSortable="false" data-sName="name" >Nome</th>
			<th data-bSortable="false" data-sName="description" >Descrizione</th>
                        <th data-bSortable="false" data-sName="actions" >Azioni</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td colspan="6" class="dataTables_empty">Carico i dati</td>
		</tr>
	</tbody>
	<tfoot>
		<tr>
			<th>Sigla</th>
			<th>Nome</th>
			<th>Descrizione</th>
                        <th>Azioni</th>
		</tr>
	</tfoot>
</table>