<link rel="stylesheet" href="js/DataTables/media/css/jquery.dataTables.css">
<h2>Categorie taxa</h2>
<a id="addCategoryTaxa" href="?task=taxa_category&amp;action=edit">Aggiungi una categoria</a>
<a id="sortCategoryTaxa" href="?task=taxa_category&amp;action=sort">Ordina le categorie</a>
<table id="categoryTaxa">
   	<thead>
		<tr>
			<th data-bSortable="false" data-sName="initials" >Sigla</th>
			<th data-bSortable="false" data-sName="name" >Nome</th>
			<th data-bSortable="false" data-sName="description" >Descrizione</th>
                        <th data-bSortable="false" data-sName="actions" >Azioni</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td colspan="6" class="dataTables_empty">Carico i dati</td>
		</tr>
	</tbody>
	<tfoot>
		<tr>
			<th>Sigla</th>
			<th>Nome</th>
			<th>Descrizione</th>
                        <th>Azioni</th>
		</tr>
	</tfoot>
</table>