<link rel="stylesheet" href="js/DataTables/media/css/jquery.dataTables.css">
<h2>Categorie taxa</h2>
<a id="listCategoryTaxa" href="?task=taxa_category">Elenco delle categorie</a>
<a id="addCategoryTaxa" href="?task=taxa_category&amp;action=edit">Aggiungi una categoria</a>
<ul id="sortCategoryTaxaList">
<?php
$taxaKindColl = new \flora\taxa\TaxaKindColl($GLOBALS['db']);
$taxaKindColl->loadAll();
foreach($taxaKindColl->getItems() as $taxaKind) : ?>
   <li id="o<?php echo $taxaKind->getData('id'); ?>"><?php echo $taxaKind->getData('name'); ?></li>
<?php endforeach; ?>
</ul>
<a id="saveCategoryTaxaOrder" href="?task=taxa_category&amp;action=save_sort">Salva</a>