<link rel="stylesheet" href="//cdn.datatables.net/1.10.3/css/jquery.dataTables.min.css">
<!--
<link rel="stylesheet" href="js/datatables/media/css/jquery.dataTables.css">
-->
<div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>/administrator.php">Home</a></p> &gt; <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>/administrator.php?task=taxa_category">Elenco delle categorie</a></p> &gt; <h2>Categorie taxa</h2>
</div>
<a id="addCategoryTaxa" href="<?php echo $GLOBALS['db']->config->baseUrl;?>/administrator.php?task=taxa_category&amp;action=edit">Aggiungi una categoria</a>
<ul id="sortCategoryTaxaList">
<?php
$taxaKindColl = new \flora\taxa\TaxaKindColl($GLOBALS['db']);
$taxaKindColl->loadAll();
foreach($taxaKindColl->getItems() as $taxaKind) : ?>
   <li id="o<?php echo $taxaKind->getData('id'); ?>"><?php echo $taxaKind->getData('name'); ?></li>
<?php endforeach; ?>
</ul>
<a id="saveCategoryTaxaOrder" href="?task=taxa_category&amp;action=save_sort">Salva</a>