<?php
$taxaObservation = new \floraobservation\TaxaObservation($GLOBALS['db']);
if (array_key_exists('cid', $_REQUEST)) {
    $_REQUEST['id'] = $this->decodeId($_REQUEST['cid']);
}
if (array_key_exists('id', $_REQUEST)) {
   $taxaObservation->loadFromId($_REQUEST['id']);
}
?><div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php">Home</a></p> &gt; <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=observation">Elenco delle osservazioni</a></p> &gt; <h2>Osservazione</h2>
</div>
<form method="post" action="#">
   <div>
      <input type="submit" name="submit" value="Salva">
      <input type="submit" name="submit_back" value="Salva e torna">
   </div>
   <div>
   <label for="datetime">Data e ora</label>
   <input id="datetime" name="datetime" readonly="readonly" value="<?php echo $taxaObservation->getData('datetime')?>">
   </div>
   <div>
   <label for="title">Titolo</label>
   <input id="title" name="title" value="<?php echo $taxaObservation->getData('title')?>">
   </div>
   <div>
   <label for="description">Descrizione</label>
   <textarea id="description" name="description"><?php echo $taxaObservation->getData('description')?></textarea>
   </div>
   <div>
   <?php if($GLOBALS['profile']->getData('role_id') == 3) : ?>
   Validata :<?php echo ($taxaObservation->getData('valid')==1 ? 'Sì' : 'No' );?>
   <?php else : ?>
   <label for="valid">Validata</label>
   <input type="checkbox" id="valid" name="valid" <?php echo ($taxaObservation->getData('valid')==1 ? 'checked' : '' );?>>
   <?php endif; ?>
   </div>
   <div>
   <?php
   $taxaObservationImageColl = $taxaObservation->getTaxaObservationImageColl();
   foreach($taxaObservationImageColl->getItems() as $taxaObservationImage):
       $imagePath = $taxaObservationImage->getPath();
       $thumbnailImageUrl = null;
        try {
        $thumbnailImageUrl = $taxaObservationImage->getUrl(array('x'=>600,'y'=>400));
        } catch (Exception $e) {}
        if (!is_null($thumbnailImageUrl)) : ?>        
        <img src="<?php echo $thumbnailImageUrl; ?>">
        <?php
            else :
            if (is_file($imagePath)) :
        ?>
        <img src="<?php echo $GLOBALS['db']->config->staticUrl.$taxaObservationImage->getUrl();?>" />
        <?php endif;
           endif;
        $transform = array();
        if ($taxaObservationImage->getData('transform') != '') {
            $transform = unserialize($taxaObservationImage->getData('transform'));
        }
        ?>
        <div>
        <label for="rotate">Rotazione</label>
        <select id="rotate" name="rotate[<?php echo $taxaObservationImage->getData('id'); ?>]">
            <option></option>
            <option value="270"<?php echo (array_key_exists('rotate',$transform) && $transform['rotate']=='270' ? ' selected="selected"' : ''); ?>>90 ° Destra</option>
            <option value="90"<?php echo (array_key_exists('rotate',$transform) && $transform['rotate']=='90' ? ' selected="selected"' : ''); ?>>90 ° Sinistra</option>
            <option value="180"<?php echo (array_key_exists('rotate',$transform) && $transform['rotate']=='180' ? ' selected="selected"' : ''); ?>>Capovolgi</option>
        </select>
        </div>
   </div>
    <p><a id="show_metadata" href="#">Visualizza metadati</a></p>
   <div id="metadata" style="display: none;">
   <?php 
    if (function_exists('exif_read_data') && is_file($imagePath)) :
    $exif = exif_read_data($taxaObservationImage->getPath());
    foreach ($exif as $key => $section) :
        if (is_array($section)) :
        foreach ($section as $name => $val) : ?>
             <?php echo $key.$name; ?>: <?php echo $val; ?><br>
        <?php endforeach;
        else: ?>
             <?php echo $key?>: <?php echo $section; ?><br>
        <?php endif;
     endforeach;
   endif;
   endforeach; ?>
   </div>
   <div>
      <input type="submit" name="submit" value="Salva">
      <input type="submit" name="submit_back" value="Salva e torna">
   </div>
</form>
<script>
//<![CDATA[
var latitude = <?php echo $taxaObservation->getPoint()->y(); ?>;
var longitude = <?php echo $taxaObservation->getPoint()->x(); ?>;
//]]>
</script>
<div id="map-canvas" style="width: 100%; height: 400px;"></div>