<?php
$taxaObservation = new \floraobservation\TaxaObservation($GLOBALS['db']);
if (array_key_exists('cid', $_REQUEST)) {
    $_REQUEST['id'] = $this->decodeId($_REQUEST['cid']);
}
if (array_key_exists('id', $_REQUEST)) {
   $taxaObservation->loadFromId($_REQUEST['id']);
}
?><div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php">Home</a></p> &gt; <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=observation">Elenco delle osservazioni</a></p> &gt; <h2>Osservazione</h2>
</div>
<form method="post" action="#">

   <div>
   <label for="datetime">Data e ora</label>
   <input id="datetime" name="datetime" readonly="readonly" value="<?php echo $taxaObservation->getData('datetime')?>">
   </div>
   <div>
   <label for="title">Titolo</label>
   <input id="title" name="title" value="<?php echo $taxaObservation->getData('title')?>">
   </div>
   <div>
   <div>
   <label for="description">Descrizione</label>
   <textarea id="description" name="description"><?php echo $taxaObservation->getData('description')?></textarea>
   </div>
   <div>
   <label for="valid">Validata</label>
   <input type="checkbox" id="valid" name="valid" <?php echo ($taxaObservation->getData('valid')==1 ? 'checked' : '' );?>>
   </div>
   <div>
   <?php
   $taxaObservationImageColl = $taxaObservation->getTaxaObservationImageColl();
   foreach($taxaObservationImageColl->getItems() as $taxaObservationImage):
        $imagePath = $taxaObservationImage->getPath();
        if (is_file($imagePath)) :
   ?>
   <img src="<?php echo $GLOBALS['db']->config->staticUrl.$taxaObservationImage->getUrl();?>" />
   <?php 
   if (function_exists('exif_read_data') && is_file($imagePath)) :
    $exif = exif_read_data($taxaObservationImage->getPath());
    foreach ($exif as $key => $section) :
        if (is_array($section)) :
        foreach ($section as $name => $val) : ?>
             <?php echo $key.$name; ?>: <?php echo $val; ?><br>
        <?php endforeach;
        else: ?>
             <?php echo $key?>: <?php echo $section; ?><br>
        <?php endif;
     endforeach;
   endif;
   endif;
   endforeach; ?>
   <div>
      <input type="submit" name="submit" value="Salva">
   </div>
</form>
<script>
//<![CDATA[
var latitude = <?php echo $taxaObservation->getPoint()->x(); ?>;
var longitude = <?php echo $taxaObservation->getPoint()->y(); ?>;
//]]>
</script>
<div id="map-canvas" style="width: 100%; height: 400px;"></div>