<?php
namespace flora\linkprovider\provider;
/**
 * Get plant reference from actaplanctorum site
 */
class Actaplanctorum implements \flora\linkprovider\provider\Provider {
   /**
    * Get plant reference from actaplanctorum site
    */
   public function retrive (\flora\taxa\Taxa $taxa) {
      if (!class_exists('Google_Client')) {
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'figlog'.DIRECTORY_SEPARATOR.'Psr'.DIRECTORY_SEPARATOR.'Log'.DIRECTORY_SEPARATOR.'LoggerInterface.php';
         
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'monolog'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Monolog'.DIRECTORY_SEPARATOR.'Logger.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'monolog'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Monolog'.DIRECTORY_SEPARATOR.'Handler'.DIRECTORY_SEPARATOR.'FormattableHandlerTrait.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'monolog'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Monolog'.DIRECTORY_SEPARATOR.'Handler'.DIRECTORY_SEPARATOR.'FormattableHandlerInterface.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'monolog'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Monolog'.DIRECTORY_SEPARATOR.'Handler'.DIRECTORY_SEPARATOR.'ProcessableHandlerTrait.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'monolog'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Monolog'.DIRECTORY_SEPARATOR.'Handler'.DIRECTORY_SEPARATOR.'ProcessableHandlerInterface.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'monolog'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Monolog'.DIRECTORY_SEPARATOR.'Handler'.DIRECTORY_SEPARATOR.'HandlerInterface.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'monolog'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Monolog'.DIRECTORY_SEPARATOR.'Handler'.DIRECTORY_SEPARATOR.'Handler.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'monolog'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Monolog'.DIRECTORY_SEPARATOR.'Handler'.DIRECTORY_SEPARATOR.'AbstractHandler.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'monolog'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Monolog'.DIRECTORY_SEPARATOR.'Handler'.DIRECTORY_SEPARATOR.'AbstractProcessingHandler.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'monolog'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Monolog'.DIRECTORY_SEPARATOR.'Handler'.DIRECTORY_SEPARATOR.'StreamHandler.php';
         
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'http-message'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'MessageInterface.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'http-message'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'RequestInterface.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'http-message'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'ResponseInterface.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'http-message'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'UriInterface.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'http-message'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'StreamInterface.php';
                  
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'psr7'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'functions.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'psr7'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'MessageTrait.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'psr7'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Request.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'psr7'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Response.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'psr7'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Stream.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'psr7'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Uri.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'psr7'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'UriResolver.php';
         
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'cache'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'CacheItemPoolInterface.php';
         
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'promises'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'functions.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'promises'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'PromiseInterface.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'promises'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Promise.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'promises'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'FulfilledPromise.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'promises'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'TaskQueueInterface.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'promises'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'TaskQueue.php';
         
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'guzzle'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'functions.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'guzzle'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'ClientInterface.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'guzzle'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Client.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'guzzle'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'HandlerStack.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'guzzle'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'RedirectMiddleware.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'guzzle'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Middleware.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'guzzle'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'RequestOptions.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'guzzle'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'PrepareBodyMiddleware.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'guzzle'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Handler'.DIRECTORY_SEPARATOR.'EasyHandle.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'guzzle'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Handler'.DIRECTORY_SEPARATOR.'CurlFactoryInterface.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'guzzle'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Handler'.DIRECTORY_SEPARATOR.'CurlFactory.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'guzzle'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Handler'.DIRECTORY_SEPARATOR.'CurlHandler.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'guzzle'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Handler'.DIRECTORY_SEPARATOR.'StreamHandler.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'guzzle'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Handler'.DIRECTORY_SEPARATOR.'CurlMultiHandler.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'guzzle'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Handler'.DIRECTORY_SEPARATOR.'Proxy.php';
         
         
         
         
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-auth-library-php'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Cache'.DIRECTORY_SEPARATOR.'MemoryCacheItemPool.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-auth-library-php'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Middleware'.DIRECTORY_SEPARATOR.'SimpleMiddleware.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-auth-library-php'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'HttpHandler'.DIRECTORY_SEPARATOR.'Guzzle6HttpHandler.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-auth-library-php'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'HttpHandler'.DIRECTORY_SEPARATOR.'HttpHandlerFactory.php';
         
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-api-php-client'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Google'.DIRECTORY_SEPARATOR.'Client.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-api-php-client'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Google'.DIRECTORY_SEPARATOR.'Service.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-api-php-client'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Google'.DIRECTORY_SEPARATOR.'Exception.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-api-php-client'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Google'.DIRECTORY_SEPARATOR.'Model.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-api-php-client'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Google'.DIRECTORY_SEPARATOR.'Collection.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-api-php-client'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Google'.DIRECTORY_SEPARATOR.'Service'.DIRECTORY_SEPARATOR.'Resource.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-api-php-client'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Google'.DIRECTORY_SEPARATOR.'Service'.DIRECTORY_SEPARATOR.'Exception.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-api-php-client'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Google'.DIRECTORY_SEPARATOR.'Http'.DIRECTORY_SEPARATOR.'REST.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-api-php-client'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Google'.DIRECTORY_SEPARATOR.'Task'.DIRECTORY_SEPARATOR.'Runner.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-api-php-client'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Google'.DIRECTORY_SEPARATOR.'AuthHandler'.DIRECTORY_SEPARATOR.'AuthHandlerFactory.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-api-php-client'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Google'.DIRECTORY_SEPARATOR.'AuthHandler'.DIRECTORY_SEPARATOR.'Guzzle6AuthHandler.php';
         
         
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-api-php-client-services'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Google'.DIRECTORY_SEPARATOR.'Service'.DIRECTORY_SEPARATOR.'Customsearch.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-api-php-client-services'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Google'.DIRECTORY_SEPARATOR.'Service'.DIRECTORY_SEPARATOR.'Customsearch'.DIRECTORY_SEPARATOR.'Search.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-api-php-client-services'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Google'.DIRECTORY_SEPARATOR.'Service'.DIRECTORY_SEPARATOR.'Customsearch'.DIRECTORY_SEPARATOR.'Result.php';
         require __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'google-api-php-client-services'.DIRECTORY_SEPARATOR.'src'.DIRECTORY_SEPARATOR.'Google'.DIRECTORY_SEPARATOR.'Service'.DIRECTORY_SEPARATOR.'Customsearch'.DIRECTORY_SEPARATOR.'Resource'.DIRECTORY_SEPARATOR.'Cse.php';
      }
      $googleClient = new \Google_Client();
      $googleClient->setDeveloperKey($taxa->getDb()->config->search->key);
       
      // create the datastore service class
      $customsearch = new \Google_Service_Customsearch($googleClient);
      $query = $taxa->getData('name');
      //$query = 'inurl:flora_info.php';
      var_dump($query);
      $optParams = array(
           'num' => '10',
           //'linkSite' => 'actaplantarum',
           'siteSearch' => 'actaplantarum.org',
           'cx'=>$taxa->getDb()->config->search->cx
           );
      $results = $customsearch->cse->listCse($query, $optParams);

      foreach($results->getItems() as $result) {
         var_dump($result);
      }
   }
}

