<!doctype html>
<html>
<head>
<link href="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('style/leaf/css/bootstrap.css');?>" rel='stylesheet' type='text/css' />
<!-- Custom Theme files -->
<link href="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('style/leaf/css/style.css');?>" rel="stylesheet" type="text/css" media="all" />
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,700,300,600,800,400' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />
<!--
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->baseUrl;?>js/jqueryui/themes/base/all.css">
-->
<?php $GLOBALS['template']->renderBlock('head'); ?>
</head>
<body>
	<!-- header-section-starts -->	
        <div id="fb-root"></div>
	<div class="header">
		<div class="container">
			<div class="col-md-4 header-left">
                            <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>">
				<img src="style/leaf/images/logo.jpg" alt="" />
                            </a>
			</div>
			<div class="col-md-8 header-right">
				<div class="top-menu">
                                    <?php $GLOBALS['template']->renderBlock('header'); ?>
				</div>
			<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
	<div class="content">
		<div class="features-section">
			<div class="container">
                            <?php $GLOBALS['template']->renderBlock('middle'); ?>
			</div>
		</div>
	</div>
	<div class="footer">
            <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
            <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
            <!--
            <script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/jquery/jquery.min.js"></script>
            <script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/jqueryui/jquery-ui.min.js"></script>
            !-->
            <script>appId="<?php echo $GLOBALS['db']->config->facebook->appId?>";</script>
	    
            <!--<script src="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('js/common/common.min.js.gz');?>"></script>-->
            <script src="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('js/common/common.js');?>"></script>
            <?php $GLOBALS['template']->renderBlock('footer'); ?>
	</div>
</body>
</html>