<!doctype html>
<html>
<head>
<link href="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('style/leaf/css/bootstrap.css.gz');?>" rel='stylesheet' type='text/css' />
<!-- Custom Theme files -->
<link href="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('style/leaf/css/style-cleaned.css.gz');?>" rel="stylesheet" type="text/css" media="all" />
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,700,300,600,800,400' rel='stylesheet' type='text/css'>
<?php if($GLOBALS['db']->config->useCDN === true) : ?>
<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />
<?php else: ?>
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->baseUrl;?>js/jqueryui/themes/base/all.css">
<?php endif; ?>
<?php $GLOBALS['template']->renderBlock('head'); ?>
</head>
<body>
        <?php if ($GLOBALS['db']->config->googleAnalitycs != '') : ?>
    	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', '<?php echo $GLOBALS['db']->config->googleAnalitycs; ?>', 'auto');
	  ga('send', 'pageview');

	</script>
        <?php endif; ?>
	<!-- header-section-starts -->	
        <div id="fb-root"></div>
	<header class="header">
		<div class="container">
			<div class="col-md-4 header-left">
                            <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>">
				<img src="style/leaf/images/logo.jpg" alt="<?php echo $GLOBALS['db']->config->siteName; ?>" />
                            </a>
			</div>
			<div class="col-md-8 header-right">
				<nav class="top-menu">
                                    <?php $GLOBALS['template']->renderBlock('header'); ?>
				</nav>
			<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
		</div>
                <?php if(sizeof($GLOBALS['db']->config->socialPages)>0) :?>
                <div class="container">
                        <div class="col-xs-offset-1 header-right">
                            <?php if($GLOBALS['db']->config->socialPages->facebook != '') : ?>
                            <a rel="nofollow" class="blank notextdecoration" href="<?php echo $GLOBALS['db']->config->socialPages->facebook; ?>">
                                <img src="style/leaf/images/fb.png" alt="Facebook" />
                            </a>
                            <?php endif; 
                            if($GLOBALS['db']->config->socialPages->googlePlus != '') : ?>
                            <a rel="publisher" class="blank notextdecoration" href="<?php echo $GLOBALS['db']->config->socialPages->googlePlus; ?>">
                                <img src="style/leaf/images/gp.png" alt="Google +" />
                            </a>
                            <?php endif; ?>
                        </div>
                </div>
                <?php endif; ?>
                <a class="github" rel="nofollow" href="https://github.com/caiofior/fioriechiavi.it">
                    <img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png">
                </a>
	</header>
	<div class="content">
		<div class="features-section">
			<div class="container">
                            <?php $GLOBALS['template']->renderBlock('middle'); ?>
			</div>
		</div>
	</div>
	<footer class="footer">
            <script>appId="<?php echo $GLOBALS['db']->config->facebook->appId?>";</script>
            <?php if($GLOBALS['db']->config->useCDN === true) : ?>
            <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
            <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
            <script src="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('js/common/common.min.js.gz');?>"></script>
            <?php else : ?>
            <script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/jquery/jquery.min.js"></script>
            <script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/jqueryui/jquery-ui.min.js"></script>
            <script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/common/common.js"></script>
            <?php endif; ?>
            <?php $GLOBALS['template']->renderBlock('footer'); ?>
	</footer>
</body>
</html>