<?php if($GLOBALS['db']->config->useCDN === true) : ?>
<script src="//cdn.jsdelivr.net/fancybox/2.1.5/jquery.fancybox.pack.js"></script>
<script src="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('js/index.min.js.gz');?>"></script>
<?php else : ?>
<script type="text/javascript" src="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('/js/fancyBox/source/jquery.fancybox.pack.js');?>"></script>
<script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/index.js"></script>
<?php endif; ?>