<?php
$title = $GLOBALS['db']->config->siteName;
$description = $title;
$taxa = $this->object;
if (
        is_object($taxa) &&
        $taxa instanceof \flora\taxa\Taxa &&
        $taxa->getData('id') != 1 &&
        $taxa->getData('name') != '') :
   $title .= ' :: '.$taxa->getRawData('taxa_kind_initials').' '.$taxa->getData('name');
   $description = $title;
   if ($taxa->getData('description') != '') {
        $description = $taxa->getData('description');
   }
   $description = strip_tags($description);
   if (strlen($description)>300) {
       $description = substr($description, 0,strpos($description,' ',300)).' …';
   }
   ?>
   <meta name="description" content="<?php echo $description;?>"/>   
   <meta property="og:description" content="<?php echo $description;?>"/>
   <meta property="og:site_name" content="<?php echo $GLOBALS['db']->config->siteName;?>"/>
   <meta property="og:title" content="<?php echo $taxa->getRawData('taxa_kind_initials').' '.$taxa->getData('name'); ?>" />
   <meta property="og:type" content="article" />
   <meta property="og:url" content="<?php echo $GLOBALS['db']->config->baseUrl;?>index.php?id=<?php echo $taxa->getData('id');?>" />
<?php
   $imageColl = $taxa->getTaxaImageColl();
   if ($imageColl->count() > 0) : ?>
   <meta property="og:image" content="<?php echo $GLOBALS['db']->config->baseUrl;?><?php echo $imageColl->getFirst()->getUrl()?>" />
<?php 
      endif;
   endif; ?>
<?php 
$cid  = null;
if (
        array_key_exists('profile', $GLOBALS) &&
        is_object($GLOBALS['profile']) &&
        $GLOBALS['profile']->getData('id') != ''
    ) {
    $cid = urlencode($this->encodeId($GLOBALS['profile']->getData('id')));
}
$rssUrl = $GLOBALS['db']->config->baseUrl.'rss.php';
if (!is_null($cid)) {
    $rssUrl .= '?key='.$cid;
}
if (
          $GLOBALS['db']->config->adsenseOverlay != '' && 
          !(
               array_key_exists('profile', $GLOBALS) &&
               is_object($GLOBALS['profile']) &&
	       (
               	       $GLOBALS['profile']->getData('role_id') == 1 ||
               	       (
	                       $GLOBALS['profile']->getData('expire') != '' &&
        	               date_diff(date_create(),date_create_from_format('Y-m-d',$GLOBALS['profile']->getData('expire')))->format('%a')>0
		       )
               )
           )
  ) { 
echo $GLOBALS['db']->config->adsenseOverlay;
} ?>
<link rel="alternate" type="application/rss+xml" title="Ultime osservazioni" href="<?php echo $rssUrl;?>">
<title><?php echo $title;?></title>
