<?php
$title = $GLOBALS['db']->config->siteName;
$description = $title;
$taxa = $this->object;
if (
        is_object($taxa) &&
        $taxa instanceof \flora\taxa\Taxa &&
        $taxa->getData('id') != 1 &&
        $taxa->getData('name') != '') :
   $title .= ' :: '.$taxa->getRawData('taxa_kind_initials').' '.$taxa->getData('name');
   $description = $title;
   if ($taxa->getData('description') != '') {
        $description = $taxa->getData('description');
   }
   $description = strip_tags($description);
   if (strlen($description)>300) {
       $description = substr($description, 0,strpos($description,' ',300)).' …';
   }
   ?>
   <meta name="description" content="<?php echo $description;?>"/>   
   <meta property="og:description" content="<?php echo $description;?>"/>
   <meta property="og:site_name" content="<?php echo $GLOBALS['db']->config->siteName;?>"/>
   <meta property="og:title" content="<?php echo $taxa->getRawData('taxa_kind_initials').' '.$taxa->getData('name'); ?>" />
   <meta property="og:type" content="article" />
   <meta property="og:url" content="<?php echo $GLOBALS['db']->config->baseUrl;?>index.php?id=<?php echo $taxa->getData('id');?>" />
<?php
   $imageColl = $taxa->getTaxaImageColl();
   if ($imageColl->count() > 0) : ?>
   <meta property="og:image" content="<?php echo $GLOBALS['db']->config->baseUrl;?><?php echo $imageColl->getFirst()->getUrl()?>" />
<?php 
      endif;
   endif; ?>
<?php 
$cid  = null;
if (
        array_key_exists('profile', $GLOBALS) &&
        is_object($GLOBALS['profile']) &&
        $GLOBALS['profile']->getData('id') != ''
    ) {
    $cid = urlencode($this->encodeId($GLOBALS['profile']->getData('id')));
}
if (is_null($cid)) : ?>
<link rel="alternate" type="application/rss+xml" title="Ultime osservazioni" href="<?php echo $GLOBALS['db']->config->baseUrl;?>rss.php">
<?php else : ?>
<link rel="alternate" type="application/rss+xml" title="Ultime osservazioni" href="<?php echo $GLOBALS['db']->config->baseUrl;?>rss.php?key=<?php echo $cid; ?>">
<?php endif; ?>
<title><?php echo $title;?></title>
