<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->baseUrl.$GLOBALS['template']->getUrlModifyTimestamp('/style/amistudio/action.css');?>" property="stylesheet">
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->baseUrl.$GLOBALS['template']->getUrlModifyTimestamp('/style/general/index.css');?>" property="stylesheet"/>
<?php if($GLOBALS['db']->config->useCDN === true) : ?>
<script src="//cdn.jsdelivr.net/fancybox/2.1.5/jquery.fancybox.min.css"></script>
<?php else : ?>
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('/js/fancyBox/source/jquery.fancybox.css'); ?>" type="text/css" media="screen" />
<?php endif; ?>
<ul>
<li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>contact.php">Contattaci</a></li>
<?php  if ($GLOBALS['profile'] instanceof \login\user\Profile) : ?>
<li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php">Amministrazione</a></li>
<li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>?logout">Esci</a></li>
<?php else: ?>
<li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>user.php">Accedi/registrati</a></li>
<?php endif; ?>
</ul>
