<?php
$title = 'Flora d\'Italia';
$dico = $this->object['dico'];
$taxa = $this->object['taxa'];
if ($taxa->getData('name') != '') {
   $taxaKind = $taxa->getTaxaKind(); 
   $title = $taxaKind->getData('initials').' '.$taxa->getData('name');
}
?><link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->baseUrl;?>/style/general/index.css">
<h1><?php echo $title; ?></h1>
<?php
if ($taxa->getData('description') != '') :
echo $taxa->getData('description');
$regionColl = $taxa->getRegionColl();
$regionColl = $regionColl->filterByAttributeValue('1','selected');
if ($regionColl->count() >0) : ?>
<div class="mapContainer">
   <img class="baseMap" src="<?php echo $GLOBALS['db']->config->baseUrl;?>/images/map/italia.png">
   <?php foreach($regionColl->getItems() as $region) : ?>
   <img class="mapRegion" src="<?php echo $GLOBALS['db']->config->baseUrl;?>/images/map/<?php echo $region->getData('id');?>.png">
   <?php endforeach; ?>
</div>
<?php endif;
endif;
$dicoItemColl = $dico->getDicoItemColl();
foreach ($dicoItemColl->getItems() as $dicoItem): 
   $label = $dicoItem->getData('text');
?>
<div>
   <?php echo str_repeat('&#160;', strlen($dicoItem->getData('id'))-1); ?>
   <?php echo strlen($dicoItem->getData('id')); ?>
   <span id="d<?php echo $dicoItem->getData('id'); ?>">
      <?php echo $label;
      $taxa = $dicoItem->getTaxa();
      if (is_numeric($taxa->getData('id'))) : 
         $taxaKind = $taxa->getTaxaKind(); ?>
      <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>?id=<?php echo $taxa->getData('id'); ?>"><?php echo $taxaKind->getData('initials'); ?> <?php echo $taxa->getData('name'); ?></a>
      <?php endif; ?>
   </span>
</div>
<?php endforeach; ?>