<div id="contenthead">
&nbsp;
</div>
<h1>Bamboo</h1>
<p>
<img class="left" src="picks/r11.jpg" alt="#"></img>

<span style="float:left;color:#000;font-size:30px;
line-height:10px; 
padding-bottom:5px;
padding-top:5px;
font-family: times;">I</span>
received an email recently asking if I had ever considered making a design with a bamboo theme?
I had not but found it to be quite fun and this is the result. <br />Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.  
</p>

<p>
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>

<dl>
<dt><a href="http://en.wikipedia.org/wiki/The_Open_Design_Community">The Open Design Community</a></dt>
<dd>The Open Design Community of designers, developers and programmers have the belief that development should follow strict standards in design, focusing on user experience and of course, web standards
</dd>

<dt><a href="#">A link to something intresting</a></dt>
<dd>This is an explanation of what you will find by visiting the link above	
This is an explanation of what you will find by visiting the link above.
</dd>
</dl>
<p>

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.  </p>
