<script src="//cdn.datatables.net/1.10.3/js/jquery.dataTables.min.js"></script>
<script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<script src="//cdn.jsdelivr.net/jquery.jeditable/1.7.3/jquery.jeditable.js"></script>
<!--
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/datatables/media/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/tinymce/tinymce.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/jeditable/jquery.jeditable.mini.js"></script>
-->
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/tinymce/jquery.tinymce.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/common/tinymce/langs/it.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/administrator/content.js"></script>