<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/datatables/media/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/tinymce/tinymce.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/tinymce/jquery.tinymce.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/common/tinymce/langs/it.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/jeditable/jquery.jeditable.mini.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/administrator/content.js"></script>