<!doctype html>
<html lang="it">
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="<?php echo $GLOBALS['template']->getUrlModifyTimestamp('style/bamboo/1.css'); ?>" />
<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />
<!--
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->baseUrl;?>js/jqueryui/themes/base/all.css">
-->
<?php $GLOBALS['template']->renderBlock('head'); ?>
</head>
<body>
<div id="header">
<div id="menu">
<?php $GLOBALS['template']->renderBlock('header'); ?>
</div>
<div id="ajaxLoader" style="display: none;"><img src="<?php echo $GLOBALS['db']->config->baseUrl;?>style/bamboo/picks/ajax-loader.gif" alt="Flora.it"/></div>
</div>

<div id="left">
&nbsp;
</div>

<div id="content">
<?php $GLOBALS['template']->renderBlock('middle'); ?>
</div>


<div id="footer">
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
<!--
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/jquery/jquery.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/jqueryui/jquery-ui.min.js"></script>
!-->
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/common/common.js"></script>
<?php $GLOBALS['template']->renderBlock('footer'); ?>
</div>
</body>
</html>
