<!doctype html>
<html lang="it">
<head>
<meta charset="utf-8">
<link rel="stylesheet" href="style/bamboo/1.css" />
<?php $GLOBALS['template']->renderBlock('head'); ?>
</head>
<body>
<div id="header">
<div id="menu">
<?php $GLOBALS['template']->renderBlock('header'); ?>
</div>
</div>

<div id="left">
&nbsp;
</div>

<div id="content">
<?php $GLOBALS['template']->renderBlock('middle'); ?>
</div>


<div id="footer">
<p>
Valid -XHTML and CSS 
</p>
</div>
<div id="loubox">
By Coollew
</div>
</body>
</html>
