<?php
$taxaObservation = $this->object;
$taxa = $taxaObservation->getTaxa();
?>
<h2>Osservazione di <?php echo $taxa->getData('taxa_kind_initials'); ?> <?php echo $taxa->getData('name'); ?> del <?php echo strftime('%e  %B  %Y',date_format(new DateTime($taxaObservation->getData('datetime')),'U')); ?></h2>
<div id="map-canvas" style='width: 100%; height: 300px;'></div>
<?php
$radius = 12;
$pointsString='[';
if (is_object($taxaObservation->getPoint()) && $taxaObservation->getPoint()->y() != '' && $taxaObservation->getPoint()->x() != '') {
    $pointsString .= '{latitude:'.$taxaObservation->getPoint()->y().',longitude:'.$taxaObservation->getPoint()->x().'},';
} ?>
<div>
    <p><strong><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>index.php?id=<?php echo $taxa->getData('id'); ?>"><?php echo $taxa->getData('taxa_kind_initials'); ?> <?php echo $taxa->getData('name'); ?></a></strong></p>
    <p><em><?php echo $taxaObservation->getData('title'); ?></em></p>
    <p><?php echo strftime('%e  %B  %Y',date_format(new DateTime($taxaObservation->getData('datetime')),'U')); ?></p>
    <p><?php echo $taxaObservation->getData('description'); ?></p>
    <?php $taxaObservationImage = $taxaObservation->getTaxaObservationImageColl(array('iDisplayStart'=>0,'iDisplayLength'=>1))->getFirst();
    $thumbnailImageUrl = null;
    try {
    $thumbnailImageUrl = $taxaObservationImage->getUrl(array('x'=>600,'y'=>400));
    } catch (Exception $e) {}
    if (!is_null($thumbnailImageUrl)) : ?>
    <a class="fancybox" href="<?php echo $taxaObservationImage->getUrl(); ?>">
    <img src="<?php echo $thumbnailImageUrl; ?>">
    </a>
    <?php endif; ?>
</div>
<?php
$pointsString .=']';
$centroid = $taxaObservation->getPoint();
?>
<script src='https://api.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.css' rel='stylesheet' />
<script>
    var mapBoxToken = "<?php echo $GLOBALS['db']->config->mapBoxToken; ?>";
    var points = <?php echo $pointsString; ?>;
    var centroid = {latitude:<?php echo $centroid->y(); ?>,longitude:<?php echo $centroid->x(); ?>};
    var radius = <?php echo $radius; ?>;
    if(typeof map == "undefined") {
     window.onload = function () {updateMap();}
    } else {
  updateMap();
    }
</script>
