<div>
   <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>">Home</a>
   <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>search.php">Ricerca avanzata</a>
   <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>map.php">Taxa presenti</a>
</div>
<h2>Ultime osservazioni botaniche</h2>
<div id="map-canvas" style='width: 100%; height: 300px;'></div>
<script src='https://api.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.css' rel='stylesheet' />
<div id="observationContent">
<?php require __DIR__.'/middleContent.phtml';?>
</div>
