<?php
$linkProvider = new flora\linkprovider\LinkProvider($GLOBALS['db']);
if (array_key_exists('id', $_REQUEST)) {
   $linkProvider->loadFromId($_REQUEST['id']);
}
?><div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php">Home</a></p> &gt; <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=link">Elenco dei Provider Link</a></p> &gt; <h2>Provider Link</h2>
</div>
<form method="post" action="#">
   <input type="hidden" id="id" name="id" value="<?php echo $linkProvider->getData('id')?>">
   <div>
   <label for="name">Nome</label>
   <input id="name" name="name" value="<?php echo htmlentities($linkProvider->getData('name'))?>">
   </div>
   <div>
      <input type="submit" name="submit" value="Salva">
   </div>
</form>
