<?php
if (!isset($floraSearch)) {
    $floraSearch = $this->object;
}
$altitudeArray = $floraSearch-> getFilteredAltitudeArray();
?>
<select id="region" name="altitude[]" multiple="multiple" size="<?php echo sizeof($altitudeArray);?>">
<?php foreach ($altitudeArray as $altitude=>$altitudeData) :
    $selected='';
    if (is_array($altitudeData) && array_key_exists('selected', $altitudeData) && $altitudeData['selected'] != '') {
        $selected=' selected="selected"';
    }
    $count = '';
    if (is_array($altitudeData) && array_key_exists('count', $altitudeData) && $altitudeData['count'] != '') {
         $count = ' ('.$altitudeData['count'].')';
    }
    ?>
    <option value="<?php echo $altitude?>"<?php echo $selected;?>><?php echo $altitude.'-'.($altitude+500).$count?></option>
<?php endforeach; ?>
</select>