<?php
if (!isset($floraSearch)) {
    $floraSearch = $this->object;
}
$biologicFormArray = $floraSearch->getFilteredBiologicFormArray(true);
?>
<select id="biologicForm" name="biologicForm[]" multiple="multiple" size="<?php echo sizeof($biologicFormArray);?>">
<?php foreach ($biologicFormArray as $biologicFormData) :
    $selected='';
    if (is_array($biologicFormData) && array_key_exists('selected', $biologicFormData) && $biologicFormData['selected'] != '') {
        $selected=' selected="selected"';
    }
    ?>
    <option value="<?php echo $biologicFormData['label'];?>"<?php echo $selected;?>><?php echo $biologicFormData['label']?> (<?php echo $biologicFormData['count']?>)</option>
<?php endforeach; ?>
</select>