<?php
if (!isset($floraSearch)) {
    $floraSearch = $this->object;
}
$communityArray = $floraSearch->getFilteredCommunityArray(true);
$communityAll = 1;
if (array_key_exists('community_all',$_REQUEST))    {
    $communityAll = $_REQUEST['community_all'];
}
?>
<input type="hidden" id="community_all" name="community_all" value="<?php echo $communityAll; ?>"/>
<select id="community" name="community[]" multiple="multiple" size="<?php echo sizeof($communityArray);?>">
<?php foreach ($communityArray as $communityData) :
    $selected='';
    if (
            $communityAll == 1 ||
            (
                is_array($communityData) &&
                array_key_exists('selected', $communityData) &&
                $communityData['selected'] != ''
            )
        ) {
        $selected=' selected="selected"';
    }
    $count = '';
    if (is_array($communityData) && array_key_exists('count', $communityData) && $communityData['count'] != '') {
         $count = ' ('.$communityData['count'].')';
    }
    ?>
    <option value="<?php echo $communityData['label'];?>"<?php echo $selected;?>><?php echo $communityData['label'].$count?></option>
<?php endforeach; ?>
</select>