<?php
if (!isset($floraSearch)) {
    $floraSearch = $this->object;
}
$floweringArray = $floraSearch-> getFilteredFloweringArray(true);
?>
<select id="flowering" name="flowering[]" multiple="multiple" size="<?php echo sizeof($floweringArray);?>">
<?php foreach ($floweringArray as $flowering=>$floweringData) :
    $selected='';
    if (is_array($floweringData) && array_key_exists('selected', $floweringData) && $floweringData['selected'] != '') {
        $selected=' selected="selected"';
    }
    ?>
    <option value="<?php echo $flowering;?>"<?php echo $selected;?>><?php echo $floweringData['label']?> (<?php echo $floweringData['count']?>)</option>
<?php endforeach; ?>
</select>