<form method="post" action="<?php echo $GLOBALS['db']->config->baseUrl;?>search.php" id="searchForm">
<input type="hidden" id="start" name="start" value="<?php echo $_REQUEST['start'];?>">
<input type="hidden" id="pagelength" name="pagelength" value="<?php echo $_REQUEST['pagelength'];?>">
<div>
    Testo:
    <input id="text" name="text">
</div>
<a href="#" class="showNext">Filtra per regione</a>
<div id="regionFilterContainer" style="display: none;">
    <a href="#" class="selectAll">Seleziona tutti</a><br/>
    <div id="regionFilter">
        <?php require __DIR__.'/regionFilter.phtml';?>
    </div>
</div>
<a href="#" class="showNext">Filtra per altitudine</a>
<div id="altitudeFilterContainer" >
    <a href="#" class="selectAll">Seleziona tutti</a><br/>
    <div id="altitudeFilter">
        <?php require __DIR__.'/altitudeFilter.phtml';?>
    </div>
</div>
<div id="searchContent">
    <?php require __DIR__.'/searchContent.phtml';?>
</div>
<input id="searchButton" type="submit" name="action" value="Cerca"/>
</form>