<form method="post" action="<?php echo $GLOBALS['db']->config->baseUrl;?>search.php" id="searchForm">
<input type="hidden" id="start" name="start" value="<?php echo $_REQUEST['start'];?>">
<input type="hidden" id="pagelength" name="pagelength" value="<?php echo $_REQUEST['pagelength'];?>">
<div>
   <label for="taxasearch">Appartenenti al taxa</label>
   <input id="taxasearch" name="taxasearch" value="">
   <input type="hidden" id="taxasearchid" name="taxasearchid" value="">
   <a id="emtpytaxasearch" class="notextdecoration" href="#" title="Cancella">◀</a>
   <span class="exportContainer" style="display: none;">
   <input id="exportButton" type="submit" name="action" value="Esporta"/>
   <label for="separator">Sep.</label>
   <select id="separator" name="separator">
       <option value="59">;</option>
       <option value="44">,</option>
       <option value="9">TAB</option>
   </select>
   <?php if (!$GLOBALS['profile'] instanceof \login\user\Profile) : ?>
   <span>Registrati e potrai scaricare tutti i taxa trovati, non una sola pagina alla volta.</span>
   <?php endif; ?>
   </span>
</div>
<div>
    <label for="text">Testo</label>
    <input id="text" name="text" type="search" value="<?php echo (array_key_exists('text', $_REQUEST) ? $_REQUEST['text']: '') ?>">
</div>
<a href="#" class="showNext">Filtro avanzato</a>
<div style="display: none;">
<div id="regionFilterContainer">
    <p><strong>Regione</strong></p>
    <a href="#" class="selectAll">Seleziona tutti</a><br/>
    <div id="regionFilter">
        <?php require __DIR__.'/regionFilter.phtml';?>
    </div>
</div>
<div id="altitudeFilterContainer">
    <p><strong>Altitudine</strong></p>
    <a href="#" class="selectAll">Seleziona tutti</a><br/>
    <div id="altitudeFilter">
        <?php require __DIR__.'/altitudeFilter.phtml';?>
    </div>
</div>
<div id="floweringFilterContainer">
    <p><strong>Periodo di fioritura</strong></p>
    <a href="#" class="selectAll">Seleziona tutti</a><br/>
    <div id="floweringFilter">
        <?php require __DIR__.'/floweringFilter.phtml';?>
    </div>
</div>
<div id="postureFilterContainer">
    <p><strong>Portamento</strong></p>
    <a href="#" class="selectAll">Seleziona tutti</a><br/>
    <div id="postureFilter">
        <?php require __DIR__.'/postureFilter.phtml';?>
    </div>
</div>
<div id="biologicFormFilterContainer">
    <p><strong>Forma biologica</strong></p>
    <a href="#" class="selectAll">Seleziona tutti</a><br/>
    <div id="biologicFormFilter">
        <?php require __DIR__.'/biologicFormFilter.phtml';?>
    </div>
</div>
</div>
<div id="searchContent">
    <?php require __DIR__.'/searchContent.phtml';?>
</div>
<input id="searchButton" type="submit" name="action" value="Cerca"/>
</form>