<?php
if (!isset($floraSearch)) {
    $floraSearch = $this->object;
}
$regionColl = $floraSearch->getFilteredRegionColl(true);
$regionAll = 1;
if (array_key_exists('region_all',$_REQUEST))    {
    $regionAll = $_REQUEST['region_all'];
} 
?>
<input type="hidden" id="region_all" name="region_all" value="<?php echo $regionAll;?>"/>
<select id="region" name="region[]" multiple="multiple" size="<?php echo $regionColl->count();?>">
<?php foreach ($regionColl->getItems() as $region) :
    $selected='';
    if (
            $regionAll == 1 ||
            $region->getRawData('selected') != ''
        ) {
        $selected=' selected="selected"';
    }
    ?>
    <option value="<?php echo $region->getData('id')?>"<?php echo $selected;?>><?php echo $region->getData('name')?> (<?php echo $region->getRawData('count')?>)</option>
<?php endforeach; ?>
</select>