<?php
if (!isset($floraSearch)) {
    $floraSearch = $this->object;
}
$regionColl = $floraSearch->getFilteredRegionColl(true);
?>
<select id="region" name="region[]" multiple="multiple" size="<?php echo $regionColl->count();?>">
<?php foreach ($regionColl->getItems() as $region) :
    $selected='';
    if ($region->getRawData('selected') != '') {
        $selected=' selected="selected"';
    }
    ?>
    <option value="<?php echo $region->getData('id')?>"<?php echo $selected;?>><?php echo $region->getData('name')?> (<?php echo $region->getRawData('count')?>)</option>
<?php endforeach; ?>
</select>