<?php
$ob_started = false;
if (
      property_exists($GLOBALS['db'],'cache') &&
		$GLOBALS['db']->cache instanceof Zend\Cache\Storage\Adapter\AbstractAdapter &&
      $GLOBALS['db']->cache->getItem('map') == ''
        ) :
   $ob_started = true;
   ob_start();
?>
<div>
   <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>">Home</a>
   <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>search.php">Ricerca avanzata</a>
   <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>observation.php">Osservazioni botaniche</a>
</div>
<h2>Mappa dei taxa presenti</h2>
<?php
$bConfig = $GLOBALS['config']->database->toArray();
$bConfig['options']['buffer_results']=false;
$db = new Zend\Db\Adapter\Adapter($bConfig);
$resultSet = $db->query('
    SELECT `node`.`taxa_id` ,
    (SELECT 
        COUNT(*) FROM `taxa_search` AS `parent` 
        WHERE 
        `node`.`lft` BETWEEN `parent`.`lft` AND `parent`.`rgt` 
    ) - 1 AS `depth` ,
    (SELECT `name` FROM `taxa` WHERE `taxa`.`id`=`node`.`taxa_id`) AS `name` ,
    ( SELECT `initials` FROM `taxa_kind` WHERE `id` =
        (SELECT `taxa_kind_id` FROM `taxa` WHERE `taxa`.`id`=`node`.`taxa_id`)
    ) AS `taxa_kind_initials`
    FROM `taxa_search` as `node`
    WHERE 
    (               
        IFNULL(LENGTH((SELECT `description` FROM `taxa` WHERE `taxa`.`id`=`node`.`taxa_id`)),0) +
        IFNULL((SELECT COUNT(`value`) FROM `taxa_attribute_value` WHERE `taxa_attribute_value`.`taxa_id`=`node`.`taxa_id`),0) +
        IFNULL((SELECT COUNT(`filename`) FROM `taxa_image` WHERE `taxa_image`.`taxa_id`=`node`.`taxa_id`),0) +
        IFNULL((SELECT COUNT(`id`) FROM `dico_item` WHERE `dico_item`.`parent_taxa_id`=`node`.`taxa_id`),0)

    ) > 0
    ORDER BY `node`.`lft`
    ',\Zend\Db\Adapter\Adapter::QUERY_MODE_EXECUTE);
$resultSet->current();
$resultSet->next();
while ($resultSet->valid()) : 
    $data = $resultSet->current();
?>
<p>
<a class="taxaPreview" href="<?php echo $GLOBALS['db']->config->baseUrl;?>?id=<?php echo $data['taxa_id']; ?>">
<?php echo str_repeat(' ', $data['depth']).$data['taxa_kind_initials'].' '.$data['name']; ?>
</a>
</p>
<?php 
    $resultSet->next();
endwhile;
else :
   echo $GLOBALS['db']->cache->getItem('map');
endif;
if ($ob_started == true) {
   $GLOBALS['db']->cache->setItem('map',ob_get_flush());
}