<?php
$taxa = new \flora\taxa\Taxa($GLOBALS['db']);
if (array_key_exists('id', $_REQUEST)) {
   $taxa->loadFromId($_REQUEST['id']);
} else {
   $taxa->setData($_REQUEST);
}
$regionColl = $taxa->getRegionColl();
?><link rel="stylesheet" href="js/plupload/js/jquery.ui.plupload/css/jquery.ui.plupload.css">
<div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>/administrator.php">Home</a></p> &gt; <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>/administrator.php?task=taxa">Elenco dei taxa</a></p> &gt; <h2>Modifica un taxa</h2>
</div>
<form method="post" action="#">
   <input type="hidden" id="id" name="id" value="<?php echo $taxa->getData('id')?>">
   <input type="hidden" id="dico_id" name="dico_id" value="<?php echo $taxa->getData('dico_id')?>">
   <input type="hidden" id="taxa_kind_id" name="taxa_kind_id" value="<?php echo $taxa->getData('taxa_kind_id')?>">
   <?php if (array_key_exists('children_dico_id', $_REQUEST)): ?>
   <input type="hidden" id="children_dico_id" name="children_dico_id" value="<?php echo $_REQUEST['children_dico_id'];?>">
   <?php endif; ?>
   <?php if (array_key_exists('children_dico_item_id', $_REQUEST)): ?>
   <input type="hidden" id="children_dico_item_id" name="children_dico_item_id" value="<?php echo $_REQUEST['children_dico_item_id'];?>">
   <?php endif; ?>
   <div>
   <label for="taxa_kind_id_name">Categoria</label>
   <input id="taxa_kind_id_name" name="taxa_kind_id_name" value="<?php echo $taxa->getData('taxa_kind_id_name')?>">
   </div>
   <div>
   <label for="name">Nome</label>
   <input id="name" name="name" value="<?php echo $taxa->getData('name')?>">
   </div>
   <div>
   <label for="description">Descrizione</label>
   <textarea id="description" name="description"><?php echo $taxa->getData('description')?></textarea>
   </div>
   <div>
   <label for="regions">Regioni</label>
   <select id="regions" name="regions[]" size="15" multiple="multiple">
      <?php
      $regionColl = $taxa->getRegionColl();
      foreach ($regionColl->getItems() as $region) : 
         $selected = '';
         if ($region->getRawData('selected')==1) {
            $selected = 'selected="delected"';   
         }
      ?>
      <option <?php echo $selected; ?> value="<?php echo $region->getData('id');?>"><?php echo $region->getData('name');?></option>
      <?php endforeach; ?>
   </select>
   </div>
   <div>
      <p>Aggiungi attibuto:</p>
      <label for="attribute_name" >Attributo</label>
      <input id="attribute_name" name="attribute_name">
      <label for="attribute_value" >Valore</label>
      <input id="attribute_value" name="attribute_value">
      <p id="attribute_error" style="display: none;">Indicare nome dell'attibuto e valore</p>
      <div id="attribute_list">
      <?php require __DIR__.'/attributeBlock.phtml'; ?>
      </div>
   </div>
   <div>
      <div id="uploader">
         <p>Il tuo browser non ha Flash, Silverlight e non supporta HTML5.</p>
      </div>
   </div>
   <div>
      <input type="submit" name="submit" value="Salva">
      <?php if ($taxa->getData('dico_id') == '') : ?>
      <input type="submit" name="submit_create_key" value="Salva e crea chiave dicotomica">
      <?php endif; ?>
   </div>
</form>
