<?php
$taxa = new \flora\taxa\Taxa($GLOBALS['db']);
$canEdit = true;
if (array_key_exists('id', $_REQUEST)) {
   $taxa->loadFromId($_REQUEST['id']);
   $canEdit = $taxa->profileCanEdit($GLOBALS['profile']);
} else {
   $taxa->setData($_REQUEST);
}
$regionColl = $taxa->getRegionColl();
if($GLOBALS['db']->config->useCDN === true) : ?>
<link rel="stylesheet" href="//cdn.jsdelivr.net/plupload/2.1.1/jquery.ui.plupload/css/jquery.ui.plupload.css">
<?php else: ?>
<link rel="stylesheet" href="js/plupload/js/jquery.ui.plupload/css/jquery.ui.plupload.css">
<?php endif; ?>
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('style/administrator/taxa.css');?>">
<div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php">Home</a></p> &gt; <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=taxa">Elenco dei taxa</a></p> &gt; <h2>Modifica un taxa</h2>
</div>
<div>
<form method="post" action="#" enctype="multipart/form-data">
   <input type="hidden" id="id" name="id" value="<?php echo $taxa->getData('id')?>">
   <input type="hidden" id="dico_id" name="dico_id" value="<?php echo $taxa->getData('dico_id')?>">
   <input type="hidden" id="taxa_kind_id" name="taxa_kind_id" value="<?php echo $taxa->getData('taxa_kind_id')?>">
   <?php if (array_key_exists('children_dico_id', $_REQUEST)): ?>
   <input type="hidden" id="children_dico_id" name="children_dico_id" value="<?php echo $_REQUEST['children_dico_id'];?>">
   <?php endif; ?>
   <?php if (array_key_exists('children_dico_item_id', $_REQUEST)): ?>
   <input type="hidden" id="children_dico_item_id" name="children_dico_item_id" value="<?php echo $_REQUEST['children_dico_item_id'];?>">
   <?php endif;
   if (array_key_exists('children_add_dico_id', $_REQUEST)): ?>
   <input type="hidden" id="children_add_dico_id" name="children_add_dico_id" value="<?php echo $_REQUEST['children_add_dico_id'];?>">
   <?php endif; ?>
   <?php if (array_key_exists('children_add_dico_item_id', $_REQUEST)): ?>
   <input type="hidden" id="children_add_dico_item_id" name="children_add_dico_item_id" value="<?php echo $_REQUEST['children_add_dico_item_id'];?>">
   <?php endif;
   if (is_numeric($taxa->getData('id')) && $taxa->getData('status') == true) : ?>
   <div>
      <div class="saved">
         <a class="blank" href="<?php echo $GLOBALS['db']->config->baseUrl;?>?id=<?php echo $taxa->getData('id')?>">Guarda pagina</a>
      </div>
      <div class="tosave" style="display: none;">
         <p>Salva la pagina per vederne l'anteprima</p>
      </div>
   </div>
   <?php endif; ?>
   <div>
      <?php if ($canEdit) : ?> 
      <input type="submit" name="submit" value="Salva">
      <?php if (!array_key_exists('children_dico_item_id', $_REQUEST) && !array_key_exists('children_add_dico_item_id', $_REQUEST)): ?>
      <input type="submit" name="submit_back" value="Salva e torna">
      <?php endif; 
      if ($taxa->getData('id') != '') : ?>
      <a class="saved" href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=dico&action=edit&id=<?php echo $taxa->getData('id')?>">Chiave dicotomica</a>
      <?php endif;
      else: ?>
      <p>Non sei abilitato alla modifica di questo taxa</p>
      <?php endif; ?>
   </div>
   <div>
   <label for="taxa_kind_id_name">Categoria</label>
   <input id="taxa_kind_id_name" name="taxa_kind_id_name" value="<?php echo $taxa->getData('taxa_kind_id_name')?>">
   </div>
   <div>
   <label for="name">Nome</label>
   <input id="name" name="name" value="<?php echo $taxa->getData('name')?>">
   </div>
   <div>
    <label for="col_id">Catalog of life ID</label>
    <input id="col_id" name="col_id" value="<?php echo htmlentities($taxa->getData('col_id'))?>"><a class="update_col_id actions update" title="Aggiorna" href="#">Aggiorna</a>
    <img class="ajaxLoader" src="<?php echo $GLOBALS['db']->config->baseUrl;?>/style/general/images/ajax-loader.gif" style="display: none;">
    <div id="col_id_list" style="display:none;"></div>
   </div>
   <div>
    <label for="eol_id">Encyclopedia of life ID</label>
    <input id="eol_id" name="eol_id" value="<?php echo htmlentities($taxa->getData('eol_id'))?>"><a class="update_eol_id actions update" title="Aggiorna" href="#">Aggiorna</a>
    <img class="ajaxLoader" src="<?php echo $GLOBALS['db']->config->baseUrl;?>/style/general/images/ajax-loader.gif" style="display: none;">
    <div id="eol_id_list" style="display:none;"></div>
   </div>
   <div>
      <p>Aggiungi attributo:</p>
      <div class="attributeTable">
         <label for="attribute_name" >Attributo</label>
         <label for="attribute_value" >Valore</label>
      </div>
      <div class="attributeTable">
         <input id="attribute_name" name="attribute_name">
         <input id="attribute_value" name="attribute_value">
      </div>
      <p id="attribute_error" style="display: none;">Indicare nome dell'attibuto e valore</p>
      <p id="attribute_missing_name" style="display: none;">Indicare nome dell'attibuto per avere dei suggerimenti sui valori</p>
      <div id="attribute_template">
      <?php 
      $attribute =new \flora\taxa\TaxaAttribute($GLOBALS['db']);
         require __DIR__.'/attributeBlock.phtml';
      ?>
      </div>
      <div id="attribute_list">
      <?php 
      $attributeColl = $taxa->getTaxaAttributeColl(); 
      foreach ($attributeColl->getItems() as $attribute) {
         require __DIR__.'/attributeBlock.phtml';
      }
      ?>
      </div>
   </div>
   <div>
      <label for="description">Descrizione</label> <a class="loadMarkup" href="#">Carica Markup</a>
      <div style="display: none;" id="description_markup_container">
         <label for="description">Incolla il codice di markup</label><br/>
         <textarea cols="80" rows="20" class="notEditable" id="description_markup" name="description_markup"></textarea><br/>
         <a class="confirmLoad" href="#">Carica</a>
         <a class="cancelLoad" href="#">Annulla</a>
      </div>
      <textarea id="description" name="description"><?php echo $taxa->getData('description')?></textarea>
   </div>
   <div>
      <div>
         <label for="regions">Regioni</label> <a class="selectAllRegions" href="#">Seleziona/Deseleziona tutte</a>
      </div>
      <div>
         
   <select id="regions" name="regions[]" size="15" multiple="multiple">
      <?php
      $regionColl = $taxa->getRegionColl();
      foreach ($regionColl->getItems() as $region) : 
         $selected = '';
         if ($region->getRawData('selected')==1) {
            $selected = 'selected="delected"';   
         }
      ?>
      <option <?php echo $selected; ?> value="<?php echo $region->getData('id');?>"><?php echo $region->getData('name');?></option>
      <?php endforeach; ?>
   </select>
         </div>
   </div>
   <div>
       <label>Aggiungi file</label>
       <input type="file" accept="image/*" name="traditional_image"/>
   </div>    
   <div>
      <div id="uploader">
         <p>Il tuo browser non ha Flash, Silverlight e non supporta HTML5.</p>
      </div>
   </div>
   <div id="image_template">
    <?php 
    $image =new \flora\taxa\TaxaImage($GLOBALS['db']);
       require __DIR__.'/imageBlock.phtml'; 
    ?>
    </div>
   <div id="image_list">
      <?php
      $imageColl = $taxa->getTaxaImageColl(); 
      foreach ($imageColl->getItems() as $image) {
      require __DIR__.'/imageBlock.phtml'; }
      ?>
      </div>
   <div>
    <label for="is_list">Voci come lista</label>
    <input type="checkbox" id="is_list" name="is_list" value="1" <?php if($taxa->getData('is_list')!='') echo 'checked="checked"';?>>
   </div>
   
   <div>
   <h5>Link esterni</h5>
   <ul>
   <?php
   $linkProviderColl = $taxa->getLinkProviderColl();
   $linkProviderColl->retriveFirst();
   foreach($linkProviderColl->getItems() as $linkProvider):?>
      <li>
          <?php if($linkProvider->getData('name') == 'actaplanctorum') : ?>
          <a class="blank" data-base="https://www.google.it/#q=site:www.actaplantarum.org+inurl:flora_info.php+" onclick="$(this).attr('href',$(this).data('base')+encodeURIComponent($('#name').val()));" href="https://www.google.it/#q=site:www.actaplantarum.org+inurl:flora_info.php+<?php echo urlencode($taxa->getData('name'));?>"><?php echo $linkProvider->getData('name');?></a>: 
          <a class="blank" href="<?php echo $linkProvider->getRawData('link');?>"><?php echo $linkProvider->getRawData('link');?></a>      
          <input name="link_<?php echo $linkProvider->getData('name');?>" value="<?php echo htmlentities($linkProvider->getRawData('link'));?>">
          <?php elseif($linkProvider->getData('name') == 'forum_actaplanctarum') : ?>
          <a class="blank" data-base="http://www.floraitaliae.actaplantarum.org/search.php?keywords=" onclick="$(this).attr('href',$(this).data('base')+encodeURIComponent($('#name').val())+'+[tscheda]');" href="http://www.floraitaliae.actaplantarum.org/search.php?keywords=<?php echo urlencode($taxa->getData('name'));?>+[tscheda]"><?php echo $linkProvider->getData('name');?></a>: 
          <a class="blank" href="<?php echo $linkProvider->getRawData('link');?>"><?php echo $linkProvider->getRawData('link');?></a>      
          <input name="link_<?php echo $linkProvider->getData('name');?>" value="<?php echo htmlentities($linkProvider->getRawData('link'));?>">
          <?php elseif($linkProvider->getData('name') == 'dryades') : ?>
          <a class="blank" href="http://dryades.units.it/cercapiante/index.php"><?php echo $linkProvider->getData('name');?></a>: 
          <a class="blank" href="<?php echo $linkProvider->getRawData('link');?>"><?php echo $linkProvider->getRawData('link');?></a>      
          <input name="link_<?php echo $linkProvider->getData('name');?>" value="<?php echo htmlentities($linkProvider->getRawData('link'));?>">
          <?php elseif($linkProvider->getData('name') == 'floritaly') : ?>
          <a class="blank" data-base="http://dryades.units.it/floritaly/index.php?procedure=simple_new&tipo=all&taxon=" onclick="$(this).attr('href',$(this).data('base')+encodeURIComponent($('#name').val()));" href="https://www.google.it/#q=site:www.actaplantarum.org+inurl:flora_info.php+<?php echo urlencode($taxa->getData('name'));?>"><?php echo $linkProvider->getData('name');?></a>: 
          <a class="blank" href="<?php echo $linkProvider->getRawData('link');?>"><?php echo $linkProvider->getRawData('link');?></a>      
          <input name="link_<?php echo $linkProvider->getData('name');?>" value="<?php echo htmlentities($linkProvider->getRawData('link'));?>">
          <?php else : ?>
          <?php echo $linkProvider->getData('name');?>: 
          <a class="blank" href="<?php echo $linkProvider->getRawData('link');?>"><?php echo $linkProvider->getRawData('link');?></a>      
          <input name="link_<?php echo $linkProvider->getData('name');?>" value="<?php echo htmlentities($linkProvider->getRawData('link'));?>">
          <?php endif ;?>
      </li>
   <?php endforeach;?>
   </ul>
   </div>   
   
   
   <?php if (is_numeric($taxa->getData('id')) && $taxa->getData('status') == true ) : ?>
   <div>
      <div class="saved">
         <a class="blank" href="<?php echo $GLOBALS['db']->config->baseUrl;?>?id=<?php echo $taxa->getData('id')?>">Guarda pagina</a>
      </div>
      <div class="tosave" style="display: none;">
         <p>Salva la pagina per vederne l'anteprima</p>
      </div>
   </div>
   <?php endif; ?>
   <div>
      <?php if ($canEdit) : ?>  
      <input type="submit" name="submit" value="Salva">
      <?php if (!array_key_exists('children_dico_item_id', $_REQUEST)): ?>
      <input type="submit" name="submit_back" value="Salva e torna">
      <?php endif; 
      if ($taxa->getData('id') != '') : ?>
      <a class="saved" href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=dico&action=edit&id=<?php echo $taxa->getData('id')?>">Chiave dicotomica</a>
      <?php endif;
      endif; ?>
   </div>
</form>
<?php if ($canEdit) : ?>    
<a href="#" class="add_dico_button">Aggiungi chiave dicotomica</a>
<form id="add_add_dico" style="display:none;" method="post" action="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=taxa&amp;action=add_dico&amp;id=<?php echo $taxa->getData('id')?>">
    <input id="dico_name" name="dico_name" value="">
    <input type="submit" name="submit" value="Aggiungi">
</form>
<?php endif; ?>
<div>
<?php
$dicoColl = $taxa->getUsedInDicoColl();
if ($dicoColl->count()>0) : ?>
<h5>Chiavi dicotomiche in cui questo taxa è presente</h5>
<ul>
<?php 
endif;
foreach($dicoColl->getItems() as $dico): ?>
    <li>
        <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=dico&action=edit&id=<?php echo $dico->getData('id'); ?>"><?php echo $dico->getRawData('taxa_kind_initials'); ?> <?php echo $dico->getData('name'); ?></a>
    </li>
<?php endforeach;
if ($dicoColl->count()>0) : ?>
</ul>    
<?php endif;
$usedAdditionalDicoColl = $taxa->getUsedAddDicoColl();
if ($usedAdditionalDicoColl->count()>0) : ?>
<h5>Chiavi dicotomiche aggiuntive in cui questo taxa è presente</h5>
<ul>
<?php 
endif;
foreach($usedAdditionalDicoColl->getItems() as $dico): ?>
    <li>
        <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=add_dico&action=edit&id=<?php echo $dico->getData('id'); ?>"><?php echo $dico->getData('name'); ?></a>
    </li>
<?php endforeach;
if ($usedAdditionalDicoColl->count()>0) : ?>
</ul>    
<?php endif;
$additionalDicoColl = $taxa->getAddDicoColl();
if ($additionalDicoColl->count()>0) : ?>
<h5>Chiavi dicotomiche aggiuntive</h5>
<ul>
<?php endif; 
foreach($additionalDicoColl->getItems() as $additionalDico): ?>
    <li>
        <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=add_dico&action=edit&id=<?php echo $additionalDico->getData('id'); ?>"><?php echo $additionalDico->getData('name'); ?></a>
        <a class="deleteAddDico actions delete" href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=taxa&amp;action=deleteadddico&amp;id=<?php echo $taxa->getData('id');?>&amp;add_dico_id=<?php echo $additionalDico->getData('id'); ?>" title="Cancella Chiave">Cancella chiave</a>
    </li>
<?php endforeach; 
if ($additionalDicoColl->count()>0) : ?>
</ul>
<?php endif; 
?>
</div>
