<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/datatables/media/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/tinymce/js/tinymce/tinymce.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/tinymce/js/tinymce/jquery.tinymce.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/administrator/taxa.js"></script>