<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/datatables/media/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/tinymce/tinymce.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/tinymce/jquery.tinymce.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/jeditable/jquery.jeditable.mini.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/plupload/js/plupload.full.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/plupload/js/jquery.ui.plupload/jquery.ui.plupload.min.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/plupload/js/i18n/it.js"></script>
<script src="<?php echo $GLOBALS['db']->config->baseUrl;?>js/administrator/taxa.js"></script>