<?php if($GLOBALS['db']->config->useCDN === true) : ?>
<link rel="stylesheet" href="//cdn.datatables.net/1.10.3/css/jquery.dataTables.min.css">
<?php else : ?>
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->baseUrl;?>/js/DataTables/media/css/jquery.dataTables.css">
<?php endif; ?>
<h2>Utenti</h2>
<div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php">Home</a></p> &gt; <h2>Utenti</h2>
</div>
<table id="users">
   	<thead>
		<tr>
                        <th data-bVisible="false" data-bSortable="true" data-asSorting="desc" data-sName="id" >id</th>
			<th data-bSortable="true" data-asSorting="desc" data-sName="email" >email</th>
			<th data-bSortable="true" data-sName="first_name" >Nome</th>
			<th data-bSortable="true" data-sName="last_name" >Cognome</th>
                        <th data-sName="active" data-sClass="isactive" >Att.</th>
                        <th data-sName="profile_role.description" >Ruolo</th>
                        <th data-bSortable="true" data-sName="login.creation_datetime" >Data registrazione</th>
                        <th data-bSortable="true" data-sName="login.last_login_datetime" >Data ultimo accesso</th>
                        <th data-bSortable="false" data-sName="actions" >Azioni</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td colspan="6" class="dataTables_empty">Carico i dati</td>
		</tr>
	</tbody>
	<tfoot>
		<tr>
                        <th>id</th>
			<th>email</th>
			<th>Nome</th>
			<th>Cognome</th>
                        <th>Att.</th>
                        <th>Ruolo</th>
                        <th>Data registrazione</th>
                        <th>Data ultimo accesso</th>
                        <th>Azioni</th>
		</tr>
	</tfoot>
</table>