<h2>Utente</h2>
<div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php">Home</a></p> &gt; <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=user">Lista utenti</a></p> &gt; <h2>Dettaglio utente</h2>
</div>
   <div>
   Nome: <?php echo $this->object->getData('first_name'); ?>
   </div>
   <div>
   Cognome: <?php echo $this->object->getData('last_name'); ?>
   </div>
   <div>
   Indirizzo: <?php echo $this->object->getData('address'); ?>
   </div>
   <div>
   Città: <?php echo $this->object->getData('city'); ?>
   </div>
   <div>
   Provincia: <?php echo $this->object->getData('province'); ?>
   </div>
   <div>
   Stato: <?php echo $this->object->getData('state'); ?>
   </div>
   <div>
   Telefono: <?php echo $this->object->getData('phone'); ?>
   </div>
<?php foreach($this->object->getUserColl()->getItems() as $user) : 
switch (get_class($user)) {
case 'login\user\Facebook' : ?>
<h3>Profilo facebook</h3>
<?php foreach ($user->getGraphValues() as $graphValue) : ?>
<div>
    <?php echo $graphValue['label']; ?>:<?php echo $graphValue['value']; ?>
</div>
<?php endforeach;
break;
case 'login\user\Login' : ?>
<h3>Profilo login</h3>
<?php foreach ($user->getData() as $graphLabel=>$graphValue) : ?>
<div>
    <?php echo $graphLabel; ?>:<?php echo $graphValue; ?>
</div>
<?php endforeach;
break;
}
endforeach; ?>
<h3>Stato</h3>
<form method="post" action="#">
    <input type="hidden" id="id" name="id" value="<?php echo $this->object->getData('id')?>">
    <div>
        <?php
        $checked = '';
        if ($this->object->getData('active') == 1) {
            $checked = ' checked="checked"';
        }
        ?>
        Attivo <input type="checkbox" name="active" id="active"<?php echo $checked;?>/>
    </div>
    <div>
    <select name="role_id" id="role_id">
    <?php
    if ($this->object->getData('role_id') == '') :?>
    <option>Seleziona un ruolo</option>
    <?php
    endif;
    $profileRoleColl = new \login\user\ProfileRoleColl($GLOBALS['db']); 
    $profileRoleColl->loadAll();
    foreach($profileRoleColl->getItems() as $profileRole): 
        $selected = '';
        if ($this->object->getData('role_id')==$profileRole->getData('id')){
            $selected = ' selected="selected"';    
        }?>
        <option value="<?php echo $profileRole->getData('id');?>"<?php echo $selected;?>><?php echo $profileRole->getData('description');?></option>    
    <?php endforeach;  ?>
    </select>
    <div>
        <div>
        Scadenza: <input id="expire" name="expire" value="<?php echo $this->object->getData('expire'); ?>">
        </div>
        <p>Aggiungi un taxa:</p>
        <div class="taxaTable">
         <input id="taxa_id" name="taxa_id">
        </div>
        <div id="taxa_list">
            <p>Elenco</p>
            <?php
            $taxaColl = $this->object->getEditableTaxaColl();
            require __DIR__.'/taxaBlock.phtml';
            ?>
        </div>
    </div>
    <div>
      <input type="submit" name="submit" value="Salva">
    </div>
    </div>
</form>

